// Auto-generated by api/seed-database.ts on 2026-01-04T23:03:23.616Z
export type paths = {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI description (this document) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    battery_level?: components["parameters"]["rowFilter.devices.battery_level"];
                    hoster_id?: components["parameters"]["rowFilter.devices.hoster_id"];
                    id?: components["parameters"]["rowFilter.devices.id"];
                    inserted_at?: components["parameters"]["rowFilter.devices.inserted_at"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                    name?: components["parameters"]["rowFilter.devices.name"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    type?: components["parameters"]["rowFilter.devices.type"];
                    updated_at?: components["parameters"]["rowFilter.devices.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["devices"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["devices"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["devices"][];
                        "text/csv": components["schemas"]["devices"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["devices"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    battery_level?: components["parameters"]["rowFilter.devices.battery_level"];
                    hoster_id?: components["parameters"]["rowFilter.devices.hoster_id"];
                    id?: components["parameters"]["rowFilter.devices.id"];
                    inserted_at?: components["parameters"]["rowFilter.devices.inserted_at"];
                    name?: components["parameters"]["rowFilter.devices.name"];
                    type?: components["parameters"]["rowFilter.devices.type"];
                    updated_at?: components["parameters"]["rowFilter.devices.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    battery_level?: components["parameters"]["rowFilter.devices.battery_level"];
                    hoster_id?: components["parameters"]["rowFilter.devices.hoster_id"];
                    id?: components["parameters"]["rowFilter.devices.id"];
                    inserted_at?: components["parameters"]["rowFilter.devices.inserted_at"];
                    name?: components["parameters"]["rowFilter.devices.name"];
                    type?: components["parameters"]["rowFilter.devices.type"];
                    updated_at?: components["parameters"]["rowFilter.devices.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["devices"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    address?: components["parameters"]["rowFilter.rooms.address"];
                    booker_id?: components["parameters"]["rowFilter.rooms.booker_id"];
                    id?: components["parameters"]["rowFilter.rooms.id"];
                    inserted_at?: components["parameters"]["rowFilter.rooms.inserted_at"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                    name?: components["parameters"]["rowFilter.rooms.name"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    updated_at?: components["parameters"]["rowFilter.rooms.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rooms"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["rooms"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["rooms"][];
                        "text/csv": components["schemas"]["rooms"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["rooms"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    address?: components["parameters"]["rowFilter.rooms.address"];
                    booker_id?: components["parameters"]["rowFilter.rooms.booker_id"];
                    id?: components["parameters"]["rowFilter.rooms.id"];
                    inserted_at?: components["parameters"]["rowFilter.rooms.inserted_at"];
                    name?: components["parameters"]["rowFilter.rooms.name"];
                    updated_at?: components["parameters"]["rowFilter.rooms.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    address?: components["parameters"]["rowFilter.rooms.address"];
                    booker_id?: components["parameters"]["rowFilter.rooms.booker_id"];
                    id?: components["parameters"]["rowFilter.rooms.id"];
                    inserted_at?: components["parameters"]["rowFilter.rooms.inserted_at"];
                    name?: components["parameters"]["rowFilter.rooms.name"];
                    updated_at?: components["parameters"]["rowFilter.rooms.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["rooms"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    created_at?: components["parameters"]["rowFilter.users.created_at"];
                    email?: components["parameters"]["rowFilter.users.email"];
                    first_name?: components["parameters"]["rowFilter.users.first_name"];
                    id?: components["parameters"]["rowFilter.users.id"];
                    last_name?: components["parameters"]["rowFilter.users.last_name"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    updated_at?: components["parameters"]["rowFilter.users.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["users"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["users"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["users"][];
                        "text/csv": components["schemas"]["users"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["users"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    created_at?: components["parameters"]["rowFilter.users.created_at"];
                    email?: components["parameters"]["rowFilter.users.email"];
                    first_name?: components["parameters"]["rowFilter.users.first_name"];
                    id?: components["parameters"]["rowFilter.users.id"];
                    last_name?: components["parameters"]["rowFilter.users.last_name"];
                    updated_at?: components["parameters"]["rowFilter.users.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    created_at?: components["parameters"]["rowFilter.users.created_at"];
                    email?: components["parameters"]["rowFilter.users.email"];
                    first_name?: components["parameters"]["rowFilter.users.first_name"];
                    id?: components["parameters"]["rowFilter.users.id"];
                    last_name?: components["parameters"]["rowFilter.users.last_name"];
                    updated_at?: components["parameters"]["rowFilter.users.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["users"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        devices: {
            /** Format: integer */
            battery_level?: number;
            /**
             * Format: uuid
             * @description Note:
             *     This is a Foreign Key to `rooms.id`.<fk table='rooms' column='id'/>
             */
            hoster_id?: string;
            /**
             * Format: uuid
             * @description Note:
             *     This is a Primary Key.<pk/>
             * @default gen_random_uuid()
             */
            id: string;
            /**
             * Format: timestamp with time zone
             * @default timezone('utc'::text, now())
             */
            inserted_at: string;
            /** Format: character varying */
            name: string;
            /**
             * Format: public.device
             * @enum {string}
             */
            type?: "display" | "keyboard" | "mouse" | "headset" | "webcam";
            /**
             * Format: timestamp with time zone
             * @default timezone('utc'::text, now())
             */
            updated_at: string;
        };
        rooms: {
            /** Format: character varying */
            address?: string;
            /**
             * Format: uuid
             * @description Note:
             *     This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
             */
            booker_id?: string;
            /**
             * Format: uuid
             * @description Note:
             *     This is a Primary Key.<pk/>
             * @default gen_random_uuid()
             */
            id: string;
            /**
             * Format: timestamp with time zone
             * @default timezone('utc'::text, now())
             */
            inserted_at: string;
            /** Format: character varying */
            name: string;
            /**
             * Format: timestamp with time zone
             * @default timezone('utc'::text, now())
             */
            updated_at: string;
        };
        users: {
            /** Format: timestamp with time zone */
            created_at?: string;
            /** Format: character varying */
            email?: string;
            /** Format: text */
            first_name?: string;
            /**
             * Format: uuid
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            id?: string;
            /** Format: text */
            last_name?: string;
            /** Format: timestamp with time zone */
            updated_at?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Limiting and Pagination */
        limit: string;
        /** @description Limiting and Pagination */
        offset: string;
        /** @description On Conflict */
        on_conflict: string;
        /** @description Ordering */
        order: string;
        /** @description Preference */
        preferCount: "count=none";
        /** @description Preference */
        preferParams: string;
        /** @description Preference */
        preferPost: "return=representation" | "return=minimal" | "return=none" | "resolution=ignore-duplicates" | "resolution=merge-duplicates";
        /** @description Preference */
        preferReturn: "return=representation" | "return=minimal" | "return=none";
        /** @description Limiting and Pagination */
        range: string;
        /** @description Limiting and Pagination */
        rangeUnit: string;
        "rowFilter.devices.battery_level": string;
        "rowFilter.devices.hoster_id": string;
        "rowFilter.devices.id": string;
        "rowFilter.devices.inserted_at": string;
        "rowFilter.devices.name": string;
        "rowFilter.devices.type": string;
        "rowFilter.devices.updated_at": string;
        "rowFilter.rooms.address": string;
        "rowFilter.rooms.booker_id": string;
        "rowFilter.rooms.id": string;
        "rowFilter.rooms.inserted_at": string;
        "rowFilter.rooms.name": string;
        "rowFilter.rooms.updated_at": string;
        "rowFilter.users.created_at": string;
        "rowFilter.users.email": string;
        "rowFilter.users.first_name": string;
        "rowFilter.users.id": string;
        "rowFilter.users.last_name": string;
        "rowFilter.users.updated_at": string;
        /** @description Filtering Columns */
        select: string;
    };
    requestBodies: {
        /** @description devices */
        devices: {
            content: {
                "application/json": components["schemas"]["devices"];
                "application/vnd.pgrst.object+json": components["schemas"]["devices"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["devices"];
                "text/csv": components["schemas"]["devices"];
            };
        };
        /** @description rooms */
        rooms: {
            content: {
                "application/json": components["schemas"]["rooms"];
                "application/vnd.pgrst.object+json": components["schemas"]["rooms"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["rooms"];
                "text/csv": components["schemas"]["rooms"];
            };
        };
        /** @description users */
        users: {
            content: {
                "application/json": components["schemas"]["users"];
                "application/vnd.pgrst.object+json": components["schemas"]["users"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["users"];
                "text/csv": components["schemas"]["users"];
            };
        };
    };
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
