/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RoomsRoomIdIndexImport } from './routes/rooms/$roomId/index'
import { Route as RoomsRoomIdDevicesDeviceIdImport } from './routes/rooms/$roomId/devices/$deviceId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsRoomIdIndexRoute = RoomsRoomIdIndexImport.update({
  id: '/rooms/$roomId/',
  path: '/rooms/$roomId/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsRoomIdDevicesDeviceIdRoute = RoomsRoomIdDevicesDeviceIdImport.update(
  {
    id: '/rooms/$roomId/devices/$deviceId',
    path: '/rooms/$roomId/devices/$deviceId',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/$roomId/': {
      id: '/rooms/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/$roomId/devices/$deviceId': {
      id: '/rooms/$roomId/devices/$deviceId'
      path: '/rooms/$roomId/devices/$deviceId'
      fullPath: '/rooms/$roomId/devices/$deviceId'
      preLoaderRoute: typeof RoomsRoomIdDevicesDeviceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdIndexRoute
  '/rooms/$roomId/devices/$deviceId': typeof RoomsRoomIdDevicesDeviceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdIndexRoute
  '/rooms/$roomId/devices/$deviceId': typeof RoomsRoomIdDevicesDeviceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/rooms/$roomId/': typeof RoomsRoomIdIndexRoute
  '/rooms/$roomId/devices/$deviceId': typeof RoomsRoomIdDevicesDeviceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms/$roomId' | '/rooms/$roomId/devices/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms/$roomId' | '/rooms/$roomId/devices/$deviceId'
  id: '__root__' | '/' | '/rooms/$roomId/' | '/rooms/$roomId/devices/$deviceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsRoomIdIndexRoute: typeof RoomsRoomIdIndexRoute
  RoomsRoomIdDevicesDeviceIdRoute: typeof RoomsRoomIdDevicesDeviceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsRoomIdIndexRoute: RoomsRoomIdIndexRoute,
  RoomsRoomIdDevicesDeviceIdRoute: RoomsRoomIdDevicesDeviceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/rooms/$roomId/",
        "/rooms/$roomId/devices/$deviceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/rooms/$roomId/": {
      "filePath": "rooms/$roomId/index.tsx"
    },
    "/rooms/$roomId/devices/$deviceId": {
      "filePath": "rooms/$roomId/devices/$deviceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
